### ISSUE TITLE
JSON schemas in bundles 

### ISSUE THREAD

**Issue by bserdar** [cloudprivacylabs/lsa#38]
If a JSON schema defines multiple entities, like the FHIR schema, we refer to the same schema in every entity definition. We should still support that, but also add a JSON schema definition at the top level of a bundle:

```
jsonSchemas:
  - id: https://hl7.org/fhir
    ref: fhir.schema.json
    overlays:
       - ovl1.json
       -  ovl2.json
```
Then, bundle references using this ID should refer to schema + overlays.
